### ISSUE TITLE
kjb

### ISSUE THREAD

**Issue by meanburrito** [MajesticWafer/wafercafe#1]
link wont work

**Comment by MajesticWafer** [comment]
How so? Do you mean that it is blocked for you?

**Comment by meanburrito** [comment]
it was like a one-day link, not working thing, idk it works now, love the website btw it's really great. Can you add cookie clicker soon that my favorite :)

**Comment by MajesticWafer** [comment]
Sure! Quite sorry for the long reply time; I was on summer holidays. I’ll try to re-add Cookie Clicker soon.

**Comment by MajesticWafer** [comment]
> it was like a one-day link, not working thing, idk it works now, love the website btw it's really great. Can you add cookie clicker soon that my favorite :)

Alrighty; Cookie Clicker is up and running! Hope you like it :)
Lags on older devices btw

**Comment by meanburrito** [comment]
Thank you so much <3
