### ISSUE TITLE
Blocked Domain

### ISSUE THREAD

**Issue by meanburrito** [MajesticWafer/wafercafe#2]
im sorry to say, but the website got blocked by contentkepper :(

**Comment by meanburrito** [comment]
omg it suddenly unblocked...

**Comment by meanburrito** [comment]
false alarm

**Comment by MajesticWafer** [comment]
What school district do you reside in? Personally, they haven’t blocked it yet in HCSD.

**Comment by meanburrito** [comment]
lssd it just got blocked fyi for real

**Comment by MajesticWafer** [comment]
Can’t do anything about that without the information of your school filter. What do you use? GoGaurdian? CKAuth?

**Comment by MajesticWafer** [comment]
Never mind. I’m stupid; Content Keeper = CKAuth

Are Vercel domains blocked for you?

**Comment by meanburrito** [comment]
content keeper

**Comment by MajesticWafer** [comment]
> content keeper

Try https://majesticwafer.github.io/
It should be up.

**Comment by MajesticWafer** [comment]
https://wafer-cafe.vercel.app/
