### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by MADKATS** [MajesticWafer/wafercafe#3]
ds player could your bring it back pls?

**Comment by MajesticWafer** [comment]
Thanks for bringing that to my attention. I must have forgotten to list that in the games.json. I’ll get to work straight away.

**Comment by MADKATS** [comment]
Ok thank you so much. are you sebastian?

**Comment by MajesticWafer** [comment]
Yup! 👍 

Anywho, it should be back now. Have fun :)

**Comment by MajesticWafer** [comment]
(fyi it’s Sebastien not Sebastian lol)

**Comment by MADKATS** [comment]
Cool i’m Kellen btw

**Comment by MajesticWafer** [comment]
👌
