### ISSUE TITLE
Widespread DS Player Virtual Keyboard Controls

### ISSUE THREAD

**Issue by MADKATS** [MajesticWafer/wafercafe#4]
Sorry for bothering you again. I have a little problem with the ds emulator… The Buttons Are Too Widespread! Is there a way to fix this in the emulator if not it’s ok.

**Comment by MajesticWafer** [comment]
I’ll check it out. Could you describe “widespread”?

**Comment by MADKATS** [comment]
The L and R are to high and the joystick and the xyba buttons are to close together in the center

**Comment by MajesticWafer** [comment]
Please send visuals.

**Comment by MajesticWafer** [comment]
In the meantime, I’ll work on restoring the controls as they were.

**Comment by MADKATS** [comment]
Ok thanks here is reference of how it was sorry for bad drawing

**Comment by MajesticWafer** [comment]
Reference where? You need to reply in the GitHub app/website for users to see it

**Comment by MADKATS** [comment]
Oh ok is that how you add images?

**Comment by MADKATS** [comment]
ok here:
![IMG_3441](https://github.com/user-attachments/assets/50a5d404-f59f-4743-8285-ffdf3e891a23)

**Comment by MajesticWafer** [comment]
So, do you want the button placement to be where the red outlines are?

**Comment by MADKATS** [comment]
Yes

**Comment by MajesticWafer** [comment]
I’ll try my best to make it more close to the original.

**Comment by MADKATS** [comment]
Thank you so much for this website and feedback
