### ISSUE TITLE
DS NO WORK :(

### ISSUE THREAD

**Issue by MADKATS** [MajesticWafer/wafercafe#5]
the ds emulator DOSE NOT WORK! i don’t know why it just say loading and never loads If you could give me a solution for this i would be very grateful.

**Comment by MajesticWafer** [comment]
What are you using the DS emulator on? Normal Safari, or is it saved on the Home Screen?

**Comment by MADKATS** [comment]
Home screen and it still has the same problem on safari

**Comment by MADKATS** [comment]
Still doesn’t work after 6 hours :(

**Comment by MajesticWafer** [comment]
What do you mean it doesn’t load?

**Comment by MADKATS** [comment]
it says loading and doesn’t load:
![IMG_3485](https://github.com/user-attachments/assets/b503a07c-10e6-43e5-8b03-c1e2a150f8dd)

**Comment by MADKATS** [comment]
Still nothing even after about 5 days

**Comment by MajesticWafer** [comment]
yuh ik

**Comment by MajesticWafer** [comment]
I’m working on it

**Comment by MADKATS** [comment]
Ok thank you so much.

**Comment by MADKATS** [comment]
Btw is this a widespread problem or only individual?

**Comment by MajesticWafer** [comment]
Widespread. I modified it at one point and it stopped working

**Comment by MajesticWafer** [comment]
I’ll stop procrastinating and actually do it now

**Comment by MajesticWafer** [comment]
Okay, should work now. I’m going to do some touch-ups though
