### ISSUE TITLE
Burrito bison crash

### ISSUE THREAD

**Issue by Evananan** [MajesticWafer/wafercafe#7]
**Describe the bug**
I was playing Burrito Bison Launcha Libre, and when i broke through the first Giant Cake Wall and was on the “New Launchador Arrives” screen, it displayed an error message saying “ An error occurred running the Unity content on this page. See your browser JavaScript console for more info. The error was: ReferenceError: Can't find variable: kongregate.” I have tried refreshing the page and going to the same place 5-10 times. 

**To Reproduce**
1. Go to ‘wafercafe.com’
2. Click on ‘burrito bison’
3. Play until breaching the first Giant Cake Wall

**Expected behavior**
I expected to acquire the second launchador, “Pineapple Spank”

**Screenshots**
![IMG_0223](https://github.com/user-attachments/assets/81563590-db17-4815-9718-69576a62c39e)

**Comment by MajesticWafer** [comment]
Unfortunately, I can’t fix this bug as I didn’t make the game. This is likely something do to with a compiling error, or a dropped variable. I apologize for any trouble caused.
