### ISSUE TITLE
YouTube for Wafercafe

### ISSUE THREAD

**Issue by Evananan** [MajesticWafer/wafercafe#8]
Hello,
I have noticed that, on all of the proxies I’ve seen that haven’t been blocked, there is always some sort of issue with YouTube. Either you need to sign in to watch videos and the captcha will not display, or the bandwidth is not large enough to allow the videos to play, I can never get YouTube to work. And so, I was wondering if you would be able to add a YouTube plugin to Wafercafe.

Thanks for considering,
A frequent user

**Comment by LutraVibes** [comment]
I'll work on this soon. Good idea.

**Comment by Evananan** [comment]
Thank you :)
